services:
  mysql:
    image: mysql:8.0
    container_name: mysql_centevi
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data: